var ownMatters =
[
  {"matterId": "1xxxxxx",
   "matterName": "fire_red", 
   "spriteFileName": "PRT_Fire_red_alpha.png", 
   "spriteWidth": 128,
   "spriteHeight": 128,
   "spritePhases": 8,
   "spriteBreak": 4,
   "animatedFileName": "PRT_Fire_red_alpha.png",
  },
  {"matterId": "2xxxxxx",
   "matterName": "fire_blue", 
   "spriteFileName": "PRT_Fire_blue_alpha.png", 
   "spriteWidth": 128,
   "spriteHeight": 128,
   "spritePhases": 8,
   "spriteBreak": 4,
   "animatedFileName": "PRT_Fire_blue_alpha.png",
  },
  {"matterId": "3xxxxxx",
   "matterName": "miku", 
   "spriteFileName": "MIKU-00.png", 
   "spriteWidth": 260,
   "spriteHeight": 260,
   "spritePhases": 36,
   "spriteBreak": 1,
   "animatedFileName": "materials/sprite/MIKU-00.gif",
  },
  {"matterId": "4xxxxxx",
   "matterName": "apple", 
   "spriteFileName": "apple_sprite.png", 
   "spriteWidth": 500,
   "spriteHeight": 500,
   "spritePhases": 7,
   "spriteBreak": 7,
   "animatedFileName": "apple_jump.gif",
  },
  {"matterId": "5xxxxxx",
   "matterName": "watermelon", 
   "spriteFileName": "watermelon_sprite.png", 
   "spriteWidth": 500,
   "spriteHeight": 500,
   "spritePhases": 6,
   "spriteBreak": 6,
   "animatedFileName": "watermelon_sprite.gif",
  },
  {"matterId": "6xxxxxx",
   "matterName": "miku2", 
   "spriteFileName": "miku3.png", 
   "spriteWidth": 300,
   "spriteHeight": 250,
   "spritePhases": 10,
   "spriteBreak": 1,
   "animatedFileName": "materials/sprite/071023_miku3.gif",
  },
  {"matterId": "7xxxxxx",
   "matterName": "blackStone", 
   "spriteFileName": "black.png", 
   "spriteWidth": 110,
   "spriteHeight": 110,
   "spritePhases": 1,
   "spriteBreak": 1,
   "animatedFileName": "black.png",
  },
  {"matterId": "8xxxxxx",
   "matterName": "whiteStone", 
   "spriteFileName": "white.png", 
   "spriteWidth": 110,
   "spriteHeight": 110,
   "spritePhases": 1,
   "spriteBreak": 1,
   "animatedFileName": "white.png",
  },
];
